config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_scope :user do
    root "devise/registrations#new"
  end

  resources :hobbies, only: [:index, :new, :create]
  resources :hobby_users, only: [:create]
  resources :users, only: [:index]
  resources :nearest_users, only: [:index]
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  has_many :hobby_users
  has_many :users, through: :hobby_users
  validates :name, presence: true, uniqueness: true
end

app/models/hobby_user.rb
class HobbyUser < ApplicationRecord
  belongs_to :hobby
  belongs_to :user
  validates :hobby_id, presence: true
  validates :user_id, presence: true
  validates :hobby_id, uniqueness: {scope: :user_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hobby_users
  has_many :hobbies, through: :hobby_users

  geocoded_by :ip_adress, :latitude => :lat, :longitude => :lon
  after_validation :geocode

  def check_nearest_users
    array = []
    User.all.each do |user|
      if (user != self)
        array.push([user, self.distance_to(user, :km)])
      end
    end
    array.sort_by!{ |x,y| y }
    array[0..4]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
   before_action :set_ip_address

   def after_sign_in_path_for(resource)
    hobbies_path
   end

   def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
   end

   def set_ip_address
     if current_user
      current_user.update(ip_adress: request.ip)
     end
   end

end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController

  def index
    @hobbies = Hobby.all
    @hobby_user = HobbyUser.new
  end

  def new
    @hobby = Hobby.new
  end

  def create
    combined_create_params = create_params
    combined_create_params[:user_id] = current_user.id
    @hobby = Hobby.create(combined_create_params)

    if @hobby.save
       redirect_to hobbies_path
    else
      render :new
    end
  end

  private

  def create_params
    params.require(:hobby).permit(:name)
  end
end

app/controllers/hobby_users_controller.rb
class HobbyUsersController < ApplicationController

  def create
    HobbyUser.create(user_id: current_user.id, hobby_id: params[:hobby_id])
    redirect_to hobbies_path
  end

end

app/controllers/nearest_users_controller.rb
class NearestUsersController < ApplicationController
  def index
    @nearest_users = current_user.check_nearest_users
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/hobby_users_helper.rb
module HobbyUsersHelper
end

app/helpers/nearest_users_helper.rb
module NearestUsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/index.html.erb
<div class="row margin_top1">
  <div class="col-sm-4"> </div>
  <div class="col-sm-4">
    <h2 class="margin_bottom1"> Hobbies </h2>

    <% @hobbies.each do |hobby| %>
      <div class="row margin_top05">
        <div class="col-sm-8"> <%= hobby.name %> </div>
        <div class="col-sm-4">
          <%= link_to('enroll', hobby_users_path(hobby_id: hobby.id), method: :post, class: "btn btn-primary") %>
        </div>
      </div>
    <% end %>

    <div class="margin_top05"> <%= link_to("Add new hobby", new_hobby_path, class: "btn btn-success") %> </div>
    <div class="margin_top05"> <%= link_to('List of users', users_path, class: "btn btn-success") %> </div>

  </div>
  <div class="col-sm-4"> </div>
</div>

app/views/hobbies/new.html.erb
<div class="row margin_top1">
  <div class="col-sm-4"> </div>
  <div class="col-sm-4">
   <h2 class="margin_bottom1"> New hobby </h2>
     <%= form_for(@hobby) do |f| %>
      <div class="row margin_top1">
        <div class="col-sm-8">
          <%= f.text_field :name, placeholder: "Add new hobby", autofocus: "on", size: "20x1", class: "form-control" %>
        </div>
        <div class="col-sm-2">
          <div class="actions">
            <%= f.submit "Save", class: "btn btn-success" %>
          </div>
        </div>
        <div class="col-sm-2 elements_in_div_center_vertically">
          <div class="actions">
            <div> <%= link_to("Cancel", hobbies_path) %> </div>
          </div>
        </div>
      <% end %>

  </div>
  <div class="col-sm-4"> </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppHobby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>

     <div class="row" style="margin-top: 0.5vw;">
      <div class="col-sm-7"> </div>
      <div class="col-sm-3">
         <span> <%= link_to('Log out', destroy_user_session_path, method: :delete) %> </span>
       </div>
      <div class="col-sm-2"> </div>
     </div>

    <% end %>
    <%= yield %>

  </body>
</html>

app/views/nearest_users/index.html.erb
<div class="row margin_top1">
  <div class="col-sm-4"> </div>
   <div class="col-sm-4">
      <h2 class="margin_bottom15"> Nearest Users </h2>
      <div class="row margin_bottom05">
        <div class="col-sm-6"> <b> User </b></div>
        <div class="col-sm-6"> <b> Distance to [km] </b></div>
      </div>
      <div class="purple_line"> </div>

      <% @nearest_users.each do |nearest_user| %>
        <div class="row margin_top05 margin_bottom05">
          <div class="col-sm-6"> <%= nearest_user[0].email %></div>
          <div class="col-sm-6">
            <% if nearest_user[1].present? %>
              <%= nearest_user[1].round(1) %>
            <% end %>
          </div>
        </div>
        <div class="purple_line"> </div>
      <% end %>

      <div class="margin_top05"> <%= link_to('List of users', users_path, class: "btn btn-success") %> </div>

    </div>
    <div class="col-sm-4"> </div>
</div>

app/views/users/index.html.erb
<div class="row margin_top1">
  <div class="col-sm-4"> </div>
  <div class="col-sm-4">
    <h2 class="margin_bottom1"> Users </h2>
    <div class="row margin_bottom05">
      <div class="col-sm-6">
         <div class="margin_top05"> <b> User </b> </div>
      </div>
      <div class="col-sm-6">
        <div class="margin_top05"> <b> Hobby </b> </div>
      </div>
    </div>
    <div class="purple_line"> </div>

    <% @users.each do |user| %>
      <div class="row margin_bottom05">
        <div class="col-sm-6">
          <div class="margin_top05">  <%= user.email %> </div>
        </div>
        <div class="col-sm-6">

          <% user.hobby_users.each do |hobby_user| %>
            <div class="margin_top05"> <%= hobby_user.hobby.name %> </div>
          <% end %>

        </div>
      </div>

      <div class="purple_line"> </div>
    <% end %>

    <div class="margin_top05"> <%= link_to('Show nearest', nearest_users_path, class: "btn btn-success") %> </div>
    <div class="margin_top05"> <%= link_to('List of hobbies', hobbies_path, class: "btn btn-success") %> </div>

  </div>
  <div class="col-sm-4"> </div>
</div>